### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by jplajpla23** [piaca/micropython-aes#1]
on this lines
data[offset:offset + block_size] = block

debug:message
'array' object does not support item assignment

**Comment by jplajpla23** [comment]
Resolved

**Comment by XDjackieXD** [comment]
Hi! I solved this by setting the data bytewise using a for loop. Did you find a better/cleaner way to fix this?

**Comment by jplajpla23** [comment]
No I resolved the problem with a for cycle byte a byte update the array

**Comment by XDjackieXD** [comment]
Ok thanks for the quick response! I solved it the same way.
